src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\PrimaryKeyTrait;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\BackupCodeInterface;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Scheb\TwoFactorBundle\Model\TrustedDeviceInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Stringable, TwoFactorInterface, TrustedDeviceInterface, BackupCodeInterface
{
    use PrimaryKeyTrait;

    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    #[ORM\Column(type: Types::STRING, length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    #[Assert\Length(max: 180)]
    private string $email;

    #[ORM\Column(type: Types::STRING)]
    #[Assert\NotBlank]
    #[Assert\Choice(callback: 'getAvailableRoles')]
    private string $role;

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING)]
    private string $password;

    #[Assert\NotBlank(groups: ['Create'])]
    private ?string $plainPassword = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Database::class, orphanRemoval: true)]
    private Collection $databases;

    #[ORM\Column(type: Types::STRING, length: 2)]
    #[Assert\NotBlank]
    #[Assert\Locale]
    private ?string $locale = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $receiveAutomaticEmails = true;

    #[ORM\Column(type: Types::STRING, nullable: true)]
    private ?string $totpSecret = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $totpEnabled = false;

    #[ORM\Column(type: Types::INTEGER)]
    private int $trustedTokenVersion = 0;

    /**
     * @var array<string>
     */
    #[ORM\Column(type: Types::JSON)]
    private array $backupCodes = [];

    public function __construct()
    {
        $this->databases = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->email;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return [$this->role];
    }

    public function getRole(): string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    /**
     * @return Collection|Database[]
     */
    public function getDatabases(): Collection
    {
        return $this->databases;
    }

    public function addDatabase(Database $database): self
    {
        if (!$this->databases->contains($database)) {
            $this->databases[] = $database;
            $database->setOwner($this);
        }

        return $this;
    }

    public function removeDatabase(Database $database): self
    {
        if ($this->databases->removeElement($database) && $database->getOwner() === $this) {
            $database->setOwner(null);
        }

        return $this;
    }

    /**
     * @return string[]
     */
    public static function getAvailableRoles(): array
    {
        return [self::ROLE_USER, self::ROLE_ADMIN];
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getReceiveAutomaticEmails(): bool
    {
        return $this->receiveAutomaticEmails;
    }

    public function setReceiveAutomaticEmails(bool $receiveAutomaticEmails): self
    {
        $this->receiveAutomaticEmails = $receiveAutomaticEmails;

        return $this;
    }

    public function getTotpSecret(): ?string
    {
        return $this->totpSecret;
    }

    public function setTotpSecret(?string $totpSecret): void
    {
        $this->totpSecret = $totpSecret;
    }

    public function isTotpEnabled(): bool
    {
        return $this->totpEnabled;
    }

    public function setTotpEnabled(bool $totpEnabled): void
    {
        $this->totpEnabled = $totpEnabled;
    }

    public function isTotpAuthenticationEnabled(): bool
    {
        return true === $this->totpEnabled && null !== $this->totpSecret;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->email;
    }

    public function getTotpAuthenticationConfiguration(): TotpConfigurationInterface
    {
        \assert(\is_string($this->totpSecret));

        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 30, 6);
    }

    public function invalidateTrustedTokenVersion(): void
    {
        ++$this->trustedTokenVersion;
    }

    public function getTrustedTokenVersion(): int
    {
        return $this->trustedTokenVersion;
    }

    /**
     * Check if it is a valid backup code.
     */
    public function isBackupCode(string $code): bool
    {
        return \in_array($code, $this->backupCodes, true);
    }

    public function invalidateBackupCode(string $code): void
    {
        $key = array_search($code, $this->backupCodes, true);
        if (false !== $key) {
            unset($this->backupCodes[$key]);
        }
    }

    public function addBackUpCode(string $backUpCode): void
    {
        if (!\in_array($backUpCode, $this->backupCodes, true)) {
            $this->backupCodes[] = $backUpCode;
        }
    }

    /**
     * @return array<string>
     */
    public function getBackupCodes(): array
    {
        return $this->backupCodes;
    }
}

src/Controller/UserController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Form\Model\EnableTwoFactorAuthenticationModel;
use App\Form\Model\SettingsModel;
use App\Form\Type\DisableTwoFactorAuthenticationType;
use App\Form\Type\EnableTwoFactorAuthenticationType;
use App\Form\Type\SettingsType;
use App\Repository\UserRepository;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Totp\TotpAuthenticatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Translation\TranslatableMessage;

#[Route('/user', name: 'app_user_')]
final class UserController extends AbstractController
{
    public function __construct(
        private readonly AdminUrlGenerator $adminUrlGenerator,
        private readonly UserPasswordHasherInterface $passwordHasher,
        private readonly UserRepository $userRepository,
        private readonly TotpAuthenticatorInterface $totpAuthenticator,
    ) {
    }

    #[Route('/settings', name: 'settings', methods: ['GET', 'POST'])]
    public function settings(Request $request): Response
    {
        $user = $this->getUser();
        \assert($user instanceof User);
        $settings = SettingsModel::createFromUser($user);
        $form = $this->createForm(SettingsType::class, $settings);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setLocale($settings->locale);
            $user->setReceiveAutomaticEmails($settings->receiveAutomaticEmails);
            $request->getSession()->set('_locale', $settings->locale);
            if (null !== $settings->newPassword) {
                $user->setPassword($this->passwordHasher->hashPassword($user, $settings->newPassword));
            }

            $this->userRepository->save($user);
            $this->addFlash('success', new TranslatableMessage('user.settings.flash_success'));

            return $this->redirectToSettings();
        }

        return $this->render('user/settings.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/enable-2fa', name: 'enable_2fa', methods: ['GET', 'POST'])]
    public function enable2fa(Request $request, UserInterface $user): Response
    {
        \assert($user instanceof User);
        if ($user->isTotpAuthenticationEnabled()) {
            $this->addFlash('danger', new TranslatableMessage('user.enable_2fa.already_enabled'));

            return $this->redirectToSettings();
        }

        if (null === $user->getTotpSecret()) {
            $user->setTotpSecret($this->totpAuthenticator->generateSecret());
            $this->userRepository->save($user);
        }

        $model = new EnableTwoFactorAuthenticationModel($user);
        $form = $this->createForm(EnableTwoFactorAuthenticationType::class, $model);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setTotpEnabled(true);
            $this->userRepository->save($user);
            $this->addFlash('success', new TranslatableMessage('user.enable_2fa.flash_success'));

            return $this->redirectToSettings();
        }

        return $this->render('user/enable_2fa.html.twig', [
            'form' => $form,
            'qr_code' => $this->totpAuthenticator->getQRContent($user),
        ]);
    }

    #[Route('/disable-2fa', name: 'disable_2fa', methods: ['GET', 'POST'])]
    public function disable2fa(Request $request, UserInterface $user): Response
    {
        \assert($user instanceof User);
        if (!$user->isTotpAuthenticationEnabled()) {
            $this->addFlash('danger', new TranslatableMessage('user.error_2fa_not_enabled'));

            return $this->redirectToSettings();
        }

        $form = $this->createForm(DisableTwoFactorAuthenticationType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setTotpSecret(null);
            $user->setTotpEnabled(false);
            $this->userRepository->save($user);
            $this->addFlash('success', new TranslatableMessage('user.disable_2fa.flash_success'));

            return $this->redirectToSettings();
        }

        return $this->render('user/disable_2fa.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/invalidate-trusted-devices', name: 'invalidate_trusted_devices', methods: ['GET'])]
    public function invalidateTrustedDevices(UserInterface $user): Response
    {
        \assert($user instanceof User);
        if (!$user->isTotpAuthenticationEnabled()) {
            $this->addFlash('danger', new TranslatableMessage('user.error_2fa_not_enabled'));
        } else {
            $user->invalidateTrustedTokenVersion();
            $this->userRepository->save($user);
            $this->addFlash('success', new TranslatableMessage('user.invalidate_trusted_devices.flash_success'));
        }

        return $this->redirectToSettings();
    }

    #[Route('/backup-codes', name: 'view_backup_codes', methods: ['GET'])]
    public function viewBackupCodes(UserInterface $user): Response
    {
        \assert($user instanceof User);
        if (!$user->isTotpAuthenticationEnabled()) {
            $this->addFlash('danger', new TranslatableMessage('user.error_2fa_not_enabled'));

            return $this->redirectToSettings();
        }

        return $this->render('user/view_backup_codes.html.twig');
    }

    #[Route('/backup-codes/generate', name: 'generate_backup_code', methods: ['POST'])]
    public function generateBackupCode(UserInterface $user): Response
    {
        \assert($user instanceof User);
        if (!$user->isTotpAuthenticationEnabled()) {
            $this->addFlash('danger', new TranslatableMessage('user.error_2fa_not_enabled'));

            return $this->redirectToSettings();
        }

        $user->addBackUpCode(bin2hex(random_bytes(16)));
        $this->userRepository->save($user);
        $this->addFlash('success', new TranslatableMessage('user.generate_backup_code.flash_success'));

        return $this->redirect($this->adminUrlGenerator->setRoute('app_user_view_backup_codes')->generateUrl());
    }

    private function redirectToSettings(): Response
    {
        return $this->redirect($this->adminUrlGenerator->setRoute('app_user_settings')->generateUrl());
    }
}

templates/user/disable_2fa.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}
{% block page_title 'user.disable_2fa.title'|trans %}

{% block page_content %}
    <p>{{ 'user.disable_2fa.intro'|trans }}</p>

    {{ form_start(form) }}
        <button type="submit" class="btn btn-danger me-1">
            <i class="fas fa-fw fa-unlock"></i>
            {{ 'user.disable_2fa.submit'|trans }}
        </button>

        <a href="{{ ea_url().setRoute('app_user_settings') }}" class="btn btn-outline-secondary">
            <i class="fas fa-fw fa-arrow-left"></i>
            {{ 'user.disable_2fa.cancel'|trans }}
        </a>
    {{ form_end(form) }}
{% endblock page_content %}

templates/user/enable_2fa.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}
{% block page_title 'user.enable_2fa.title'|trans %}
{% form_theme form '@EasyAdmin/crud/form_theme.html.twig' %}

{% block page_content %}
    <p>{{ 'user.enable_2fa.intro'|trans }}</p>

    {{ form_start(form) }}
        <div class="row">
            {{ form_row(form.code, { row_attr: { class: 'col col-md-6' }, attr: { autofocus: '' } }) }}
        </div>

        <img src="{{ get_qr_code_from_string(qr_code) }}" alt="{{ 'user.enable_2fa.qr_code'|trans }}" class="mt-2" style="width: 300px;">

        <div class="mt-3">
            <button type="submit" class="btn btn-primary me-1">
                <i class="fas fa-fw fa-lock"></i>
                {{ 'user.enable_2fa.submit'|trans }}
            </button>

            <a href="{{ ea_url().setRoute('app_user_settings') }}" class="btn btn-outline-secondary">
                <i class="fas fa-fw fa-arrow-left"></i>
                {{ 'user.enable_2fa.cancel'|trans }}
            </a>
        </div>
    {{ form_end(form) }}
{% endblock page_content %}

templates/user/settings.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block page_title 'user.settings.title'|trans %}
{% form_theme form '@EasyAdmin/crud/form_theme.html.twig' %}
{% block page_content %}
    <div class="row">
        <div class="col-12 col-md-4">
            <h3>{{ 'user.settings.form_title'|trans }}</h3>

            {{ form_start(form) }}
                {{ form_row(form.locale) }}
                {{ form_row(form.currentPassword) }}
                {{ form_row(form.newPassword) }}
                {{ form_row(form.receiveAutomaticEmails) }}

                <p>
                    <button type="submit" class="btn btn-primary" name="_submit">
                        <i class="fas fa-fw fa-check"></i>
                        {{ 'user.settings.submit'|trans }}
                    </button>
                </p>
            {{ form_end(form) }}
        </div>
        <div class="col-12 col-md-4">
            <h3 class="mb-4">{{ 'user.settings.2fa.title'|trans }}</h3>

            <p>
                {{ 'user.settings.2fa.status.title'|trans }}
                <span class="badge bg-{{ app.user.totpAuthenticationEnabled ? 'success' : 'danger' }}">
                    {{ "user.settings.2fa.status.#{app.user.totpAuthenticationEnabled ? 'active' : 'inactive'}"|trans }}
                </span>
            </p>

            {% if app.user.totpAuthenticationEnabled %}
                <a href="{{ ea_url().setRoute('app_user_view_backup_codes') }}" class="btn btn-outline-primary me-2 mb-2">
                    <i class="fas fa-fw fa-list"></i>
                    {{ 'user.settings.2fa.view_backup_codes'|trans }}
                </a>

                <a href="{{ ea_url().setRoute('app_user_disable_2fa') }}" class="btn btn-outline-danger me-2 mb-2">
                    <i class="fas fa-fw fa-lock-open"></i>
                    {{ 'user.settings.2fa.disable'|trans }}
                </a>

                <a href="{{ ea_url().setRoute('app_user_invalidate_trusted_devices') }}" class="btn btn-outline-warning">
                    <i class="fas fa-fw fa-trash"></i>
                    {{ 'user.settings.2fa.invalidate_trusted_devices'|trans }}
                </a>
            {% else %}
                <a href="{{ ea_url().setRoute('app_user_enable_2fa') }}" class="btn btn-outline-primary">
                    <i class="fas fa-fw fa-lock"></i>
                    {{ 'user.settings.2fa.enable'|trans }}
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/user/view_backup_codes.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}
{% block page_title 'user.view_backup_codes.title'|trans %}

{% block page_content %}
    <p>{{ 'user.view_backup_codes.intro'|trans }}</p>

    {% if app.user.backupCodes|length > 0 %}
        <ul>
            {% for backup_code in app.user.backupCodes %}
                <li>{{ backup_code }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="alert alert-info">{{ 'user.view_backup_codes.none'|trans }}</div>
    {% endif %}

    <div class="mt-3">
        <form method="post" action="{{ ea_url().setRoute('app_user_generate_backup_code') }}">
            <button type="submit" class="btn btn-primary me-1">
                <i class="fas fa-fw fa-plus"></i>
                {{ 'user.view_backup_codes.generate_new_code'|trans }}
            </button>

            <a href="{{ ea_url().setRoute('app_user_settings') }}" class="btn btn-outline-secondary">
                <i class="fas fa-fw fa-arrow-left"></i>
                {{ 'user.view_backup_codes.back'|trans }}
            </a>
        </form>
    </div>
{% endblock page_content %}